#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = iar.targets.arm.M3{1,0,7.70,1
#
project.xrm3: package/cfg/project.xrm3.mak

clean::
	-$(RM) package/cfg/project.xrm3.mak
